[package]
name = "blackbody"
version = "0.1.0"
authors = ["just-do-halee <just.do.halee@gmail.com>"]
description = "Blockchain node based on consensus compression algorithm."
license = "LGPL-3.0-only"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"